### ISSUE TITLE
Empty folder leeds to spinlock

### ISSUE THREAD

**Issue by masgo** [ftpgrab/ftpgrab#33] opened 2018-01-08 22:53 UTC
Hi,
first of all thanks for this great script!

When trying to use it, my example directory structure contained an empty folder which lead to the script hanging forever. 

With debug enabled I could see how it loops. The only thing that changes is the `srchash`
As soon as I added an empty file to this folder, the problem was gone.

Here is an excerpt of the debug output (I censored the real names)

```
#DEBUG checkfolder: curl --silent --list-only --globoff -u *****:***** --ftp-ssl "ftp://example.com:21/AN%5fEMPTY%5fFOLDER//////////////////////"
#DEBUG lineClean: /
#DEBUG basename: /
#DEBUG srcfile: /AN_EMPTY_FOLDER//////////////////////
#DEBUG srcfileproc: /AN%5fEMPTY%5fFOLDER//////////////////////
#DEBUG srcfileshort: AN_EMPTY_FOLDER//////////////////////
#DEBUG srcfileshort2: AN_EMPTY_FOLDER//////////////////////
#DEBUG srchash: 0e087c88145ec4a845f2f9d575560747
#DEBUG srcsize:
#DEBUG destfile: /tmp/seedbox/AN_EMPTY_FOLDER//////////////////////
#DEBUG destsize: N/A
#DEBUG vregex: AN_EMPTY_FOLDER//////////////////////
#DEBUG checkfolder: curl --silent --list-only --globoff -u *****:***** --ftp-ssl "ftp://example.com:21/AN%5fEMPTY%5fFOLDER////////////////////////"
#DEBUG lineClean: /
#DEBUG basename: /
#DEBUG srcfile: /AN_EMPTY_FOLDER////////////////////////
#DEBUG srcfileproc: /AN%5fEMPTY%5fFOLDER////////////////////////
#DEBUG srcfileshort: AN_EMPTY_FOLDER////////////////////////
#DEBUG srcfileshort2: AN_EMPTY_FOLDER////////////////////////
#DEBUG srchash: 123b24923553082f8beee2004ed55496
#DEBUG srcsize:
#DEBUG destfile: /tmp/seedbox/AN_EMPTY_FOLDER////////////////////////
#DEBUG destsize: N/A
#DEBUG vregex: AN_EMPTY_FOLDER////////////////////////
#DEBUG checkfolder: curl --silent --list-only --globoff -u *****:***** --ftp-ssl "ftp://example.com:21/AN%5fEMPTY%5fFOLDER//////////////////////////"
#DEBUG lineClean: /
#DEBUG basename: /
#DEBUG srcfile: /AN_EMPTY_FOLDER//////////////////////////
#DEBUG srcfileproc: /AN%5fEMPTY%5fFOLDER//////////////////////////
#DEBUG srcfileshort: AN_EMPTY_FOLDER//////////////////////////
#DEBUG srcfileshort2: AN_EMPTY_FOLDER//////////////////////////
#DEBUG srchash: af9471cd3ecc2715fdf5c276accbae98
#DEBUG srcsize:
#DEBUG destfile: /tmp/seedbox/AN_EMPTY_FOLDER//////////////////////////
#DEBUG destsize: N/A
#DEBUG vregex: AN_EMPTY_FOLDER//////////////////////////
#DEBUG checkfolder: curl --silent --list-only --globoff -u *****:***** --ftp-ssl "ftp://example.com:21/AN%5fEMPTY%5fFOLDER////////////////////////////"
#DEBUG lineClean: /
#DEBUG basename: /
#DEBUG srcfile: /AN_EMPTY_FOLDER////////////////////////////
#DEBUG srcfileproc: /AN%5fEMPTY%5fFOLDER////////////////////////////
#DEBUG srcfileshort: AN_EMPTY_FOLDER////////////////////////////
#DEBUG srcfileshort2: AN_EMPTY_FOLDER////////////////////////////
#DEBUG srchash: 4515adb96595251e22d416fd7c8bbbb9
#DEBUG srcsize:
#DEBUG destfile: /tmp/seedbox/AN_EMPTY_FOLDER////////////////////////////
#DEBUG destsize: N/A
#DEBUG vregex: AN_EMPTY_FOLDER////////////////////////////

```

**Comment by crazy-max** [comment] 2018-01-08 23:00
Hi @masgo, thanks for your feedback, I will take a look asap

**Comment by crazy-max** [comment] 2018-01-11 13:49
Can you post your config file please ? And if possible the structure of the FTP_SOURCES (command `tree`).
Thanks

**Comment by masgo** [comment] 2018-01-11 14:03
I only have FTP access to the server, therefore I can not do a `tree`.  But if I do the curl command from the debug logs:

`curl --silent --list-only --globoff -u xxxxx:xxxxx --ftp-ssl ftp://xxxxxxxx:21/THE_EMPTY_FOLDER/  > response.txt`

Then the response file has 0 Bytes.  

The name of the empty folder contains of characters, numbers and the `_` sign.

config: 
```
# This file is an integral part of FTPGrab.
# More info : https://ftpgrab.github.io

# General
DIR_DEST="/tmp/seedbox"
EMAIL_LOG=""
DEBUG=0

# FTP
FTP_HOST="xxxxxxxxxx"
FTP_PORT="21"
FTP_USER="xxxxxxxxxx"
FTP_PASSWORD="xxxxxxxxxx"
FTP_SOURCES="/"

# FTP security (only with curl method)
FTP_SECURE=1
FTP_CHECK_CERT=1

# Download
DL_METHOD="curl"
DL_USER=""
DL_GROUP=""
DL_CHMOD=""
DL_REGEX=""
DL_EXCLUDE_REGEX=""
DL_RETRY=3
DL_RESUME=0
DL_SHUFFLE=0
DL_HIDE_SKIPPED=1
DL_HIDE_PROGRESS=1
DL_CREATE_BASEDIR=0

# Hash
HASH_ENABLED=1
HASH_TYPE="md5"
HASH_STORAGE="sqlite3"
```

**Comment by crazy-max** [comment] 2018-01-11 14:09
Ok thanks

**Comment by crazy-max** [comment] 2018-01-11 14:29
@masgo I cannot reproduce your issue.
Can you post your full log if possible ?
And follow those steps please : https://ftpgrab.github.io/doc/reporting-issue/
Thanks

**Comment by crazy-max** [comment] 2018-01-13 17:54
@masgo Some feedback to help me investigate on your issue ?

**Comment by crazy-max** [comment] 2018-01-15 08:06
Ok thanks @masgo

**Comment by crazy-max** [comment] 2018-02-07 18:00
@masgo Oh i completely forgot your issue 😕 I will make a new release this week to solve it! Sorry!

**Comment by masgo** [comment] 2018-02-08 02:03
@crazy-max hey no problem! This is a free and open source project. I have seen (much) longer bugfix times from software where I was a paying customer. So don't worry, you are doing a great job.

**Comment by crazy-max** [comment] 2018-03-04 23:33
@masgo I still haven't been able to reproduce your problem on several configurations.

Here is a simple test I have made with a FTP source to **/test/test_empty/** containing :

```
[-] empty
 |  a.pdf
```

The FTPGrab result is :

```
FTPGrab v4.3.1 (ftpgrab - 2018/03/05 00:22:05)
--------------
Config: ftpgrab
Script PID: 20
Log file: /var/log/ftpgrab/ftpgrab-20180305002205.log
FTP sources count: 1
FTP secure: 1
Download method: curl
Resume downloads: 0
Shuffle file/folder list: 0
Hash type: md5
Hash storage: text
Hash file: /opt/ftpgrab/hash/ftpgrab.txt
--------------
#DEBUG FTP_SRC: /test/test_empty/
#DEBUG DIR_DEST: /data
#DEBUG DIR_DEST_REF: /data/
Source: ftp://10.0.0.2:21/test/test_empty/
Destination: /data/
Checking connection to ftp://10.0.0.2:21/test/test_empty/...
#DEBUG checkConnection: curl --silent --retry 1 --retry-delay 5 --globoff --ftp-ssl --insecure ftp://10.0.0.2:21/test/test_empty/
Successfully connected!
--------------
#DEBUG checkfolder: curl --silent --list-only --globoff -u *****:***** --ftp-ssl --insecure "ftp://10.0.0.2:21/test/test%5fempty/a.pdf/"
#DEBUG lineClean: a.pdf
#DEBUG basename: a.pdf
#DEBUG srcfile: /test/test_empty/a.pdf
#DEBUG srcfileproc: /test/test%5fempty/a.pdf
#DEBUG srcfileshort: a.pdf
#DEBUG srcfileshort2: a.pdf
#DEBUG srchash: f87a4d24fcc05251afdb56cc24a5ca5d
#DEBUG srcsize: 35360997
#DEBUG destfile: /data/a.pdf
#DEBUG destsize: N/A
#DEBUG vregex: a.pdf
Process file: a.pdf
Hash: f87a4d24fcc05251afdb56cc24a5ca5d
Size: 33.72 Mb
Status: Never downloaded...
Start download to /data/a.pdf... Please wait...
#DEBUG Download command: curl --globoff -u *****:***** --ftp-ssl --insecure "ftp://10.0.0.2:21/test/test%5fempty/a.pdf" -o "/data/a.pdf"
File successfully downloaded!
Time spent: 00:00:36
--------------
#DEBUG checkfolder: curl --silent --list-only --globoff -u *****:***** --ftp-ssl --insecure "ftp://10.0.0.2:21/test/test%5fempty/empty/"
#DEBUG lineClean: empty/
#DEBUG basename: empty
#DEBUG srcfile: /test/test_empty/empty
#DEBUG srcfileproc: /test/test%5fempty/empty
#DEBUG srcfileshort: empty
#DEBUG srcfileshort2: empty
#DEBUG srchash: a2e4822a98337283e39f7b60acf85ec9
#DEBUG srcsize:
#DEBUG destfile: /data/empty
#DEBUG destsize: N/A
#DEBUG vregex: empty
Change the ownership recursively of 'Destination' path to docker:docker
--------------
Finished...
```

Can you make the same test and clean the destination directory ?
What is your linux distrib ?
And can you test on an other computer ? (or with the Docker image)

Thanks

**Comment by crazy-max** [comment] 2018-04-20 01:02
Close due to inactivity

**Comment by fletcherm** [comment] 2018-08-14 12:16
Hi crazy-max,

I may have a fix for this problem. Please see my commit here -- https://github.com/fletcherm/ftpgrab/commit/e78c8443316f1e93e6a7b4fd88b9be7cb6e72704

I was experiencing the same problem as masgo -- ftpgrab stuck listing the same empty directory over and over again, appending a `/` each subsequent time but getting the same result.

The linked commit breaks from the recursive function if the result from listing the directory is empty and is working well given my limited testing.

A few caveats:

1. I considered adding some unit tests, but with the way things are structured, that'd be non-trivial and may introduce more problems. I am hoping you have a more exhaustive system test suite that can validate this change.
2. I only tested this with `curl` -- `wget` appears to be more chatty when listing an empty directory, and in fact shows a `.listing` file for empty directories. `curl` simply returns blank. Anyway, I'm hoping your test suite can validate this change is ok for `wget` as well.
3. I have not extensively tested this yet -- and will not until I get home later today or this weekend. I will let you know how well it turns out after I can point it at a real ftp server with a good mix of empty / non-empty directories.
4. I am not sure why you were unable to reproduce this problem. I'm on Alpine Linux 3.8 and `curl` version 7.61.0. It is consistently returning blank when listing an empty directory. Have you tried a structure like this?
```
[-]
  [-] empty1
    [-] empty2
```

Hope this helps. I will let you know how my more extensive testing goes this weekend.

**Comment by crazy-max** [comment] 2018-08-15 09:55
Hi @fletcherm, thanks for your input on this. I will check this out asap.

**Comment by fletcherm** [comment] 2018-08-15 11:18
Thanks, crazy-max.

I did some overnight testing against a live system. The patch appears to be holding up well. I am eager to learn what your testing finds.

A couple of other caveats:

1. My bash scripting skills are not great so I am open to alternative, better ways to test for empty results.
2. It would be wise to trim whitespace from the `_$FILES` variable before testing for emptiness, incase `curl` or `wget` return some spaces or newlines. I am hoping you know of a good way to do this.

Thanks again for creating this tool and investigating this problem!

**Comment by crazy-max** [comment] 2018-08-15 12:03
Ok thanks, i make some test today and it seems to only happen if `FTP_SOURCES=/`.

**Comment by fletcherm** [comment] 2018-08-15 12:53
Cool! I am glad you were able to reproduce it.

For what it's worth, my `FTP_SOURCES` has about a half dozen entries. Either way I am glad you found the problem. Thanks for the updates!

**Comment by crazy-max** [comment] 2018-08-15 12:54
And thanks to you to help me figures this out :)

**Closed by crazy-max** 2018-08-15 12:54 UTC
Labels: bug
