### ISSUE TITLE
directory name has "." bug

### ISSUE THREAD

**Issue by foolin** [ftpgrab/ftpgrab#53] opened 2019-06-05 03:22 UTC
### Behaviour

When ftp server has directory name contains ".",  read direcotry files fail.

#### Steps to reproduce this issue

1. Create direcotry like "data-2019.1-12"
2. Upload a file to the diredtory

#### Expected behaviour

> I can download the file is ok!

#### Actual behaviour

> I skip the direcotry, and can't found file.

### Configuration

* FTPGrab version (5.0.0) :  5.3.0
* Platform (windows/linux/freebsd/macos) :  Linux
* Remote FTP (Pure-FTPd) or SFTP (OpenSSH) server:  ftp

### Problem

When i debug for it, i found ftp read dir that code:
```
// ReadDir fetches the contents of a directory, returning a list of os.FileInfo's
func (c *Client) ReadDir(path string) ([]os.FileInfo, error) {
	return c.ftp.ReadDir(regexp.QuoteMeta(path))
}
```
It's egexp.QuoteMeta function report the bug, it convert:
```
"data-2019.1-12" -> "data-2019\.1-12"
````

But the ftp server not exists folder "data-2019\.1-12"!

When I remove "regexp.QuoteMeta", it run ok!

**Comment by crazy-max** [comment] 2019-06-05 17:08
Hi @foolin, thanks for your report but I cannot reproduce your issue :

```
Wed, 05 Jun 2019 17:00:55 UTC DBG goftp: 0.622 #1 sending command MLSD /test/brackets/
Wed, 05 Jun 2019 17:00:56 UTC DBG goftp: 0.641 #1 got 150-Accepted data connection

scanner.Text=type=cdir;sizd=4096;modify=20190605165943;UNIX.mode=0755;UNIX.uid=1001;UNIX.gid=1001;unique=903g5a20111; .
scanner.Text=type=pdir;sizd=4096;modify=20190605165943;UNIX.mode=0755;UNIX.uid=1001;UNIX.gid=1001;unique=903g5a20111; ..
scanner.Text=type=dir;sizd=4096;modify=20190605170000;UNIX.mode=0755;UNIX.uid=1001;UNIX.gid=1001;unique=903g5ae05d1; test.dot
scanner.Text=type=dir;sizd=4096;modify=20190502171601;UNIX.mode=0755;UNIX.uid=1001;UNIX.gid=1001;unique=903g5a2001a; test_[brack]ets
scanner.Text=type=dir;sizd=4096;modify=20190502205011;UNIX.mode=0755;UNIX.uid=1001;UNIX.gid=1001;unique=903g5a20112; test_[brackets
parseMLST: type=cdir;sizd=4096;modify=20190605165943;UNIX.mode=0755;UNIX.uid=1001;UNIX.gid=1001;unique=903g5a20111; .
parseMLST: type=pdir;sizd=4096;modify=20190605165943;UNIX.mode=0755;UNIX.uid=1001;UNIX.gid=1001;unique=903g5a20111; ..
parseMLST: type=dir;sizd=4096;modify=20190605170000;UNIX.mode=0755;UNIX.uid=1001;UNIX.gid=1001;unique=903g5ae05d1; test.dot
parseMLST: type=dir;sizd=4096;modify=20190502171601;UNIX.mode=0755;UNIX.uid=1001;UNIX.gid=1001;unique=903g5a2001a; test_[brack]ets
parseMLST: type=dir;sizd=4096;modify=20190502205011;UNIX.mode=0755;UNIX.uid=1001;UNIX.gid=1001;unique=903g5a20112; test_[brackets
Wed, 05 Jun 2019 17:00:56 UTC DBG goftp: 0.694 #1 was ready
Wed, 05 Jun 2019 17:00:56 UTC DBG goftp: 0.694 #1 sending command PASV
Wed, 05 Jun 2019 17:00:56 UTC DBG goftp: 0.714 #1 got 227-Entering Passive Mode (10,0,0,1,196,132)
Wed, 05 Jun 2019 17:00:56 UTC DBG goftp: 0.715 #1 opening data connection to 10.0.0.1:50308
Wed, 05 Jun 2019 17:00:56 UTC DBG goftp: 0.737 #1 upgrading data connection to TLS
Wed, 05 Jun 2019 17:00:56 UTC DBG goftp: 0.738 #1 sending command MLSD /test/brackets/test\.dot
Wed, 05 Jun 2019 17:00:56 UTC DBG goftp: 0.759 #1 got 150-Accepted data connection

scanner.Text=type=cdir;sizd=4096;modify=20190605170000;UNIX.mode=0755;UNIX.uid=1001;UNIX.gid=1001;unique=903g5ae05d1; .
scanner.Text=type=pdir;sizd=4096;modify=20190605165943;UNIX.mode=0755;UNIX.uid=1001;UNIX.gid=1001;unique=903g5a20111; ..
scanner.Text=type=file;size=6997;modify=20190604180019;UNIX.mode=0644;UNIX.uid=1001;UNIX.gid=1001;unique=903g5ae05d2; somefile
parseMLST: type=cdir;sizd=4096;modify=20190605170000;UNIX.mode=0755;UNIX.uid=1001;UNIX.gid=1001;unique=903g5ae05d1; .
parseMLST: type=pdir;sizd=4096;modify=20190605165943;UNIX.mode=0755;UNIX.uid=1001;UNIX.gid=1001;unique=903g5a20111; ..
parseMLST: type=file;size=6997;modify=20190604180019;UNIX.mode=0644;UNIX.uid=1001;UNIX.gid=1001;unique=903g5ae05d2; somefile
Wed, 05 Jun 2019 17:00:56 UTC INF --------
Wed, 05 Jun 2019 17:00:56 UTC INF Checking /test/brackets/test.dot/somefile.nfo
Wed, 05 Jun 2019 17:00:56 UTC INF Never downloaded
Wed, 05 Jun 2019 17:00:56 UTC INF Downloading file (6.997kB) to /ftpgrab/ftpgrab/bin/braket/test.dot/somefile.nfo...
Wed, 05 Jun 2019 17:00:56 UTC DBG goftp: 0.812 #1 was ready
Wed, 05 Jun 2019 17:00:56 UTC DBG goftp: 0.813 #1 sending command TYPE I
Wed, 05 Jun 2019 17:00:56 UTC DBG goftp: 0.834 #1 got 200-TYPE is now 8-bit binary
Wed, 05 Jun 2019 17:00:56 UTC DBG goftp: 0.835 #1 sending command SIZE /test/brackets/test.dot/somefile.nfo
Wed, 05 Jun 2019 17:00:56 UTC DBG goftp: 0.855 #1 got 213-6997
Wed, 05 Jun 2019 17:00:56 UTC DBG goftp: 0.856 #1 was ready
Wed, 05 Jun 2019 17:00:56 UTC DBG goftp: 0.857 #1 was ready
Wed, 05 Jun 2019 17:00:56 UTC DBG goftp: 0.858 #1 sending command TYPE I
Wed, 05 Jun 2019 17:00:56 UTC DBG goftp: 0.879 #1 got 200-TYPE is now 8-bit binary
Wed, 05 Jun 2019 17:00:56 UTC DBG goftp: 0.880 #1 sending command PASV
Wed, 05 Jun 2019 17:00:56 UTC DBG goftp: 0.901 #1 got 227-Entering Passive Mode (10,0,0,1,196,76)
Wed, 05 Jun 2019 17:00:56 UTC DBG goftp: 0.902 #1 opening data connection to 10.0.0.1:50252
Wed, 05 Jun 2019 17:00:56 UTC DBG goftp: 0.924 #1 upgrading data connection to TLS
Wed, 05 Jun 2019 17:00:56 UTC DBG goftp: 0.925 #1 sending command RETR /test/brackets/test.dot/somefile.nfo
Wed, 05 Jun 2019 17:00:56 UTC DBG goftp: 0.947 #1 got 150-Accepted data connection
6.8 kbytes to download
Wed, 05 Jun 2019 17:00:56 UTC INF File successfully downloaded!
Wed, 05 Jun 2019 17:00:56 UTC INF Time spent: 228 milliseconds
```

Can you post your full log ?

**Comment by foolin** [comment] 2019-06-06 02:51
Oh, let me see how it reproduce。

**Comment by foolin** [comment] 2019-06-06 03:44
@crazy-max You try this directory name: "/2015\xc4\xea\u012b\xce\xf7\xb8\xe7\xbd\xf8\xbf\u06ba\xa3\xb9\xd8\xca\xfd\xbe\xdd/\u012b\xce\xf7\xb8\xe7-\xbd\xf8\xbf\xda-2015.1-12"


In chinese:  "/2015年墨西哥进口海关数据/墨西哥-进口-2015.1-12"

May be the sample as charset problem...

**Comment by crazy-max** [comment] 2019-06-06 10:28
Ok so this a regression from your PR. I'm closing this issue and will start a review on your PR when I've got some time.

**Closed** 2019-06-06 10:30 UTC

**Comment by DrAg0n141** [comment] 2021-07-29 11:13
Hi, i have exactly the same Problem. All Folders with "." in Name are ignored. And not appered in LOG i can only see the Folder with "FTPGRAB_SERVER_FTP_LOGTRACE=true". I think the Problem is that is escapes the "." with \ and then the Folder is not reachable.
